"""add indexes cascades and model fixes

Revision ID: 7e306e98b2a4
Revises: 0012
Create Date: 2026-07-23 15:19:48.262329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e306e98b2a4'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brands_owner_id'), 'brands', ['owner_id'], unique=False)
    op.drop_constraint(op.f('brands_owner_id_fkey'), 'brands', type_='foreignkey')
    op.create_foreign_key(None, 'brands', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'brands',
        'Brands monitored for AI visibility',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_user_id'), 'campaign_recipients', ['user_id'], unique=False)
    op.drop_constraint(op.f('campaign_recipients_campaign_id_fkey'), 'campaign_recipients', type_='foreignkey')
    op.drop_constraint(op.f('campaign_recipients_user_id_fkey'), 'campaign_recipients', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_recipients', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'campaign_recipients', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.drop_constraint(op.f('credit_transactions_user_id_new_fkey'), 'credit_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'credit_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('credit_wallets', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('credit_wallets_user_id_new_fkey'), 'credit_wallets', type_='foreignkey')
    op.create_foreign_key(None, 'credit_wallets', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_monitored_queries_brand_id'), 'monitored_queries', ['brand_id'], unique=False)
    op.create_table_comment(
        'monitored_queries',
        'Queries monitored for AI visibility',
        existing_comment=None,
        schema=None
    )
    op.alter_column('query_results', 'competitors_mentioned',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_query_results_query_id'), 'query_results', ['query_id'], unique=False)
    op.create_index(op.f('ix_query_results_scan_id'), 'query_results', ['scan_id'], unique=False)
    op.create_table_comment(
        'query_results',
        'Individual LLM query results',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_scans_brand_id'), 'scans', ['brand_id'], unique=False)
    op.create_table_comment(
        'scans',
        'AI visibility scans',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'scans',
        existing_comment='AI visibility scans',
        schema=None
    )
    op.drop_index(op.f('ix_scans_brand_id'), table_name='scans')
    op.drop_table_comment(
        'query_results',
        existing_comment='Individual LLM query results',
        schema=None
    )
    op.drop_index(op.f('ix_query_results_scan_id'), table_name='query_results')
    op.drop_index(op.f('ix_query_results_query_id'), table_name='query_results')
    op.alter_column('query_results', 'competitors_mentioned',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_table_comment(
        'monitored_queries',
        existing_comment='Queries monitored for AI visibility',
        schema=None
    )
    op.drop_index(op.f('ix_monitored_queries_brand_id'), table_name='monitored_queries')
    op.drop_constraint(None, 'credit_wallets', type_='foreignkey')
    op.create_foreign_key(op.f('credit_wallets_user_id_new_fkey'), 'credit_wallets', 'users', ['user_id'], ['id'])
    op.alter_column('credit_wallets', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('credit_transactions_user_id_new_fkey'), 'credit_transactions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_constraint(None, 'campaign_recipients', type_='foreignkey')
    op.drop_constraint(None, 'campaign_recipients', type_='foreignkey')
    op.create_foreign_key(op.f('campaign_recipients_user_id_fkey'), 'campaign_recipients', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('campaign_recipients_campaign_id_fkey'), 'campaign_recipients', 'campaigns', ['campaign_id'], ['id'])
    op.drop_index(op.f('ix_campaign_recipients_user_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table_comment(
        'brands',
        existing_comment='Brands monitored for AI visibility',
        schema=None
    )
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.create_foreign_key(op.f('brands_owner_id_fkey'), 'brands', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_brands_owner_id'), table_name='brands')
    # ### end Alembic commands ###
