export const queryKeys = {
  brands: (page: number = 1, search: string = "") => ["brands", page, search] as const,
  queries: (brandId: string) => ["queries", brandId] as const,
  queriesTable: (brandId: string, page: number, perPage: number, q: string) => ["queriesTable", brandId, page, perPage, q] as const,
  scans: (brandId: string, page: number = 1, perPage: number = 20) => ["scans", brandId, page, perPage] as const,
  dashboard: (brandId: string) => ["dashboard", brandId] as const,
  drilldown: (brandId: string, queryId: string) => ["drilldown", brandId, queryId] as const,
  llmDrilldown: (brandId: string, llmName: string) => ["llmDrilldown", brandId, llmName] as const,
  competitorDrilldown: (brandId: string, competitorName: string) => ["competitorDrilldown", brandId, competitorName] as const,
  credits: ["credits"] as const,
  creditPackages: ["creditPackages"] as const,
  user: ["user"] as const,
  campaigns: ["campaigns"] as const,
  campaign: (id: string) => ["campaigns", id] as const,
  adminUsers: (search?: string) => ["adminUsers", search ?? ""] as const,
  adminStats: ["adminStats"] as const,
};
